yandex_cloud_id = "b1gm5cnlfgcnmeq4an1v"
folder_id    = "b1ggvhbs15psoc1vgtkc"
key_json     = "/mnt/cloud-netology/key.json"
vm_user      = "caevert"
vm_user_nat  = "caevertnat"
ssh_key_path = "/home/caevert/.ssh/id_rsa.pub"
lamp_image_id = "fd827b91d99psvq5fjit"
